METRO_AREAS = {
  # geo_coordinates and a radius in mi.
  # specify closest :city_kw for metros that do not correspond to an actual city: like orange county
  los_angeles:          { state_kw: :ca, name: :los_angeles,           lat: 0, lng:0, radius:0 },
  san_francisco:        { state_kw: :ca, name: :san_francisco,         lat: 0, lng:0, radius:0 },
  new_york:             { state_kw: :ny, name: :new_york,              lat: 0, lng:0, radius:0 },
  austin:               { state_kw: :tx, name: :austin,                lat: 0, lng:0, radius:0 },
  orange_county:        { state_kw: :ca, name: :orange_county,         lat: 0, lng:0, radius:0, city_kw: :irvine },
  san_antonio:          { state_kw: :tx, name: :san_antonio,           lat: 0, lng:0, radius:0 },
  raleigh_durham_cary:  { state_kw: :nc, name: :raleigh_durham_cary,   lat: 0, lng:0, radius:0, city_kw: :raleigh },
}

METRO_ALIASES = {
  # enter any valuable keyword that is an alias for a metro
  ny:               :new_york,
  nyc:              :new_york,

  la:               :los_angeles,
  usc:              :los_angeles,
  venice:           :los_angeles,
  burbank:          :los_angeles,
  pasadena:         :los_angeles,
  glendale:         :los_angeles,
  hollywood:        :los_angeles,
  santa_monica:     :los_angeles,
  beverly_hills:    :los_angeles,
  west_hollywood:   :los_angeles,
  marina_del_rey:   :los_angeles,
  north_hollywood:  :los_angeles,

  oc:               :orange_county,

  sf:               :san_francisco,
  sunnyvale:        :san_francisco,
  san_jose:         :san_francisco,
  mountain_view:    :san_francisco,
  palo_alto:        :san_francisco,
  cupertino:        :san_francisco,
  los_gatos:        :san_francisco,
  saratoga:         :san_francisco,
  fremont:          :san_francisco,
  campbell:         :san_francisco,
  santa_cruz:       :san_francisco,
  santa_clara:      :san_francisco,
  san_mateo:        :san_francisco,
  redwood_city:     :san_francisco,
  foster_city:      :san_francisco,
  menlo_park:       :san_francisco,
  stanford:         :san_francisco,
  monterey:         :san_francisco,
  fremont:          :san_francisco,
  milpitas:         :san_francisco,
  los_altos:        :san_francisco,
  belmont:          :san_francisco,
  san_carlos:       :san_francisco,
  gilroy:           :san_francisco,
  morgan_hill:      :san_francisco,

  rtp:              :raleigh_durham_cary,
  raleigh:          :raleigh_durham_cary,
  durham:           :raleigh_durham_cary,
  cary:             :raleigh_durham_cary,
  chapel_hill:      :raleigh_durham_cary,
  holly_springs:    :raleigh_durham_cary,
  morrisville:      :raleigh_durham_cary,
  apex:             :raleigh_durham_cary,
  research_triangle:        :raleigh_durham_cary,
  research_triangle_park:   :raleigh_durham_cary,
}
