development:
  host: localhost
  database: food_truck_development

test:
  host: localhost
  database: food_truck_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
